# -*- coding: utf-8 -*-
"""Контент новой главной. Один источник — пять языков.
Позиционирование: Business Advisory & Solutions (бриф 25.09.2026)."""

PHONE_HREF = "tel:+18182690416"
PHONE_TEXT = "+1 (818) 269-0416"
WA = "https://wa.me/18182690416"
DIAG = "https://scan.prodigylab.studio/diagnostic?lang="
SCAN = "https://scan.prodigylab.studio/scan?lang="

L = {}

L['ru'] = dict(
  scan_secondary='Проверить сайт с помощью AI',
  locale='ru_RU', home='/', scan_lang='ru',
  title='Prodigy LAB — разбор и решение бизнес-задач',
  desc='Бизнес приходит к нам с проблемой, а не за услугой. Мы определяем, где именно теряются деньги, и либо решаем сами, либо подключаем проверенного профильного партнёра.',
  eyebrow='Business Advisory & Solutions',
  h1='Где-то в вашем бизнесе утекают деньги. Чаще всего — не там, где кажется',
  lede='Владелец обычно знает симптом: платежи заблокировали, реклама не окупается, заявки теряются между каналами. Чего нет — взгляда со стороны на то, какая из этих проблем сейчас самая дорогая и что чинить первым.',
  cta1='Расскажите, что не работает', cta2='Что мы разбираем',
  note='Первичный разбор бесплатно · без обязательств · без обязательного созвона',
  quote='Вам не нужен ещё один подрядчик. Сначала нужен честный разбор бизнеса.',
  photo_alt='Александр, основатель Prodigy LAB',
  s1_eyebrow='Что мешает бизнесу расти',
  s1_h2='Шесть мест, где действующие компании тихо теряют деньги',
  s1_lede='Мы работаем со всеми шестью. Часть решаем сами, часть — через профильного партнёра, которого проверили. И говорим, что именно из этого что, до того как вы на что-то соглашаетесь.',
  s2_eyebrow='Как это устроено',
  s2_h2='Сначала вы получаете разбор — и только потом кто-то предлагает работу',
  s3_eyebrow='Кто мы',
  s3_h2='Компания, которая сама всё это строила, а не каталог ссылок',
  s3_p1='Prodigy LAB годами собирал и чинил то, через что бизнес продаёт: магазины, сайты, рекламу, конверсию, переписку с клиентами. Эта работа никуда не делась — и именно она позволяет отличить проблему инфраструктуры от проблемы маркетинга.',
  s3_p2='Консалтинг вырос из неё. Клиенты приходили с задачами, которые вообще не про сайт: процессор отключил приём платежей, банк закрыл счёт, функцию в компании никто не ведёт. Отвечать только на ту часть, что попадает в наш прайс-лист, было бесполезно.',
  no_title='Чего мы не делаем',
  no_p1='Мы не платёжный процессор и не банк. Мы не одобряем merchant-аккаунты и не открываем счета, и не можем гарантировать, что это сделает провайдер. Мы не оказываем юридических, налоговых, инвестиционных и иных регулируемых финансовых консультаций и не занимаемся регистрацией юрлиц, визами и иммиграцией.',
  no_p2='Если задача требует лицензированного специалиста — мы так и скажем.',
  facts_title='Компания',
  facts=[('Юрлицо','Platonaire LLC'),('База','Калифорния, США'),('Работаем с','США и международно'),
         ('Языки','RU · EN · ES · PT · DE'),('Делаем сами','Сайты · E-comm · Реклама'),('Первичный разбор','Бесплатно')],
  remote='Prodigy LAB работает удалённо. Офиса, куда можно приехать, у нас нет, и мы не приписываем себе городов, в которых не присутствуем.',
  final_eyebrow='Бесплатный первичный разбор',
  final_h2='Опишите проблему. Мы скажем, в чём она, по нашему мнению, на самом деле',
  final_lede='Бесплатно, ни к чему не обязывает, созвон необязателен. Если ваша ситуация вне того, чем мы занимаемся, вы получите об этом честный ответ, а не коммерческое предложение.',
  final_cta1='Начать разбор', final_cta2='Написать напрямую',
  call='Позвонить', foot_priv='Политика конфиденциальности',
  foot_legal='Prodigy LAB не является платёжным процессором, банком или лицензированным поставщиком юридических, налоговых или финансовых консультаций.',
  nav=[('#problems','Что разбираем'),('#how','Как устроено'),('#who','Кто мы')],
  problems=[
    ('01 — Платежи','Процессор перестал вас устраивать','Аккаунт заблокировали, деньги удерживают, растут chargebacks — или ваша ниша тихо не нужна текущему провайдеру.',['Аккаунт закрыт или на проверке','Высокий процент chargebacks','Подписочная или high-risk модель','Нужен резерв или другие рельсы']),
    ('02 — Банкинг','Банк не подходит под то, как вы работаете','Особенно если компания в США, а основатель за рубежом — или банк перестал соответствовать модели бизнеса.',['Счёт закрыт или заморожен','Основатель за рубежом, юрлицо в США','Открытие счёта из-за границы','Нужна альтернативная инфраструктура']),
    ('03 — Рост','Трафик и бюджет не превращаются в выручку','На бумаге привлечение работает, на практике — нет. Обычно ломается в одном конкретном месте, а не везде сразу.',['Клики есть, заказов нет','Растёт стоимость клиента','Проседает конкретный шаг воронки']),
    ('04 — Операции','Работа держится на том, что кто-то помнит','Заявки в четырёх местах, CRM, которой никто не верит, отчёт, собираемый руками в воскресенье.',['Разрозненные системы','Ручные повторяющиеся процессы','У цифровой части нет владельца']),
    ('05 — Инфраструктура','Функции, ради которых нанимать дорого, а игнорировать — дороже','Логистика, зарплаты, безопасность, рабочие инструменты: нужны постоянно и редко окупают отдельную ставку.',['Фулфилмент и 3PL','Расчёт зарплат и HR','Безопасность и комплаенс']),
    ('06 — Присутствие','Витрина, по которой вас и оценивают','Сайт и e-commerce — то, что мы много лет делали и продолжаем делать своими руками.',['Пересборка сайта или магазина','Конверсия и оформление заказа','Инфраструктура интернет-магазина']),
  ],
  steps=[
    ('Расскажите, что не работает','Короткая структурированная анкета, а не форма «напишите нам». Чем занимается бизнес, что сломалось, что уже пробовали и насколько это срочно.'),
    ('Мы разбираем — бесплатно','Возвращаемся с тем, что считаем настоящим ограничением, стоит ли это решать сейчас и какие есть реальные пути. Если задача не наша — скажем прямо.'),
    ('Решаем сами или передаём','Что в нашей компетенции — делаем сами. Остальное уходит профильному партнёру, которого мы проверили. Что именно из этого что, вы знаете заранее.'),
  ],
)

L['en'] = dict(
  scan_secondary='Run a free AI website scan',
  locale='en_US', home='/en/', scan_lang='en',
  title='Prodigy LAB — Business Advisory & Solutions',
  desc='Businesses come to us with a problem, not a service request. We work out where the money is actually going, then either solve it ourselves or bring in a vetted specialist partner.',
  eyebrow='Business Advisory & Solutions',
  h1='Something in your business is costing you money. Usually not where you think',
  lede='Owners normally know the symptom: payments blocked, ads that do not pay back, enquiries lost between channels. What is missing is an outside read on which of those is most expensive right now, and what to fix first.',
  cta1='Tell us what is not working', cta2='What we handle',
  note='Free initial assessment · no obligation · no call required',
  quote='You do not need another contractor. First you need an honest read on the business.',
  photo_alt='Aleksandr, founder of Prodigy LAB',
  s1_eyebrow="What's holding your business back",
  s1_h2='Six places where established businesses lose money quietly',
  s1_lede='We work across all six. Some we solve directly, others through a specialist partner we have vetted — and we tell you which is which before you commit to anything.',
  s2_eyebrow='How it works',
  s2_h2='You get the diagnosis before anyone proposes work',
  s3_eyebrow='Who we are',
  s3_h2='An operating company, not a directory of links',
  s3_p1='Prodigy LAB spent years building and fixing the systems businesses sell through: stores, websites, advertising, conversion, customer conversations. That work continues, and it is what lets us tell an infrastructure problem from a marketing one.',
  s3_p2='Advisory grew out of it. Clients kept arriving with problems that were not web problems at all — a processor that dropped them, a bank that closed an account, a function nobody owned. Answering only the part that fit our service list was not useful to them.',
  no_title='What we do not do',
  no_p1='We are not a payment processor and not a bank. We do not approve merchant accounts or open bank accounts, and we cannot guarantee a provider will. We do not provide legal, tax, investment or other regulated financial advice, and we do not handle company formation, visas or immigration.',
  no_p2='Where a licensed specialist is required, that is exactly what we will tell you.',
  facts_title='Company',
  facts=[('Legal entity','Platonaire LLC'),('Based','California, USA'),('Works with','US & international'),
         ('Languages','RU · EN · ES · PT · DE'),('Built in-house','Web · E-comm · Ads'),('Initial assessment','Free')],
  remote='Prodigy LAB is a remote company. We do not keep a walk-in office, and we do not claim locations we do not have.',
  final_eyebrow='Free initial assessment',
  final_h2='Describe the problem. We will tell you what we think it actually is',
  final_lede='No cost, no obligation, no requirement to get on a call. If your situation is outside what we handle, you will be told that instead of receiving a proposal.',
  final_cta1='Start the assessment', final_cta2='Message us directly',
  call='Call us', foot_priv='Privacy Policy',
  foot_legal='Prodigy LAB is not a payment processor, a bank, or a licensed provider of legal, tax or financial advice.',
  nav=[('#problems','What we solve'),('#how','How it works'),('#who','Who we are')],
  problems=[
    ('01 — Payments','Your processor stopped working for you','Accounts suspended, funds held, chargebacks climbing, or a vertical your current provider quietly does not want.',['Account closed or under review','High chargeback ratio','Subscription or high-risk billing','Needs redundancy or alternative rails']),
    ('02 — Banking','Banking that does not fit how you operate','Especially for US companies with founders abroad, or a bank that no longer matches the business model.',['Account frozen or closed','Foreign founder, US entity','Opening business banking from abroad','Needs alternative infrastructure']),
    ('03 — Growth','Traffic and spend that do not turn into revenue','Acquisition works on paper and fails in practice — usually in one specific place, not everywhere.',['Clicks without orders','Rising cost per customer','A known step of the funnel underperforming']),
    ('04 — Operations','Work that depends on someone remembering','Leads in four inboxes, a CRM nobody trusts, reporting assembled by hand on Sunday night.',['Fragmented systems','Manual, repeatable processes','No single owner for the digital side']),
    ('05 — Infrastructure','Functions too small to hire for, too costly to ignore','Fulfilment, payroll, security, business tooling — necessary, recurring, rarely worth a full salary.',['Fulfilment and 3PL','Payroll and HR','Security and compliance']),
    ('06 — Digital presence','The storefront your buyers actually judge you on','Website and e-commerce infrastructure: the part we have built for years and still build ourselves.',['Site or store rebuild','Conversion and checkout','E-commerce infrastructure']),
  ],
  steps=[
    ('Tell us what is not working','A short structured intake, not a contact form. What the business does, what broke, what you have already tried, and how urgent it is.'),
    ('We assess it — at no cost','We come back with what we think the real constraint is, whether it is worth solving now, and what the realistic paths are. If it is not ours to solve, we say so.'),
    ('We solve it, or route it','Work inside our own competence we do ourselves. Anything else goes to a specialist partner we have checked — and you are told upfront which it is.'),
  ],
)

L['es'] = dict(
  scan_secondary='Analizar el sitio con IA',
  locale='es_ES', home='/es/', scan_lang='es',
  title='Prodigy LAB — Asesoría y Soluciones de Negocio',
  desc='Las empresas acuden a nosotros con un problema, no a pedir un servicio. Determinamos dónde se está yendo el dinero y lo resolvemos nosotros o incorporamos a un socio especializado verificado.',
  eyebrow='Business Advisory & Solutions',
  h1='Algo en tu negocio te está costando dinero. Normalmente no donde crees',
  lede='El dueño suele conocer el síntoma: pagos bloqueados, publicidad que no se paga sola, consultas que se pierden entre canales. Lo que falta es una lectura externa de cuál de esos problemas sale más caro ahora y qué arreglar primero.',
  cta1='Cuéntanos qué no funciona', cta2='Qué abordamos',
  note='Evaluación inicial gratuita · sin compromiso · sin llamada obligatoria',
  quote='No necesita otro proveedor. Primero necesita una lectura honesta del negocio.',
  photo_alt='Aleksandr, fundador de Prodigy LAB',
  s1_eyebrow='Qué frena a tu negocio',
  s1_h2='Seis lugares donde las empresas establecidas pierden dinero en silencio',
  s1_lede='Trabajamos en los seis. Algunos los resolvemos directamente, otros con un socio especializado que hemos verificado — y te decimos cuál es cuál antes de que te comprometas a nada.',
  s2_eyebrow='Cómo funciona',
  s2_h2='Primero recibes el diagnóstico y solo después alguien propone trabajo',
  s3_eyebrow='Quiénes somos',
  s3_h2='Una empresa operativa, no un directorio de enlaces',
  s3_p1='Prodigy LAB lleva años construyendo y arreglando aquello con lo que las empresas venden: tiendas, sitios web, publicidad, conversión, conversaciones con clientes. Ese trabajo continúa, y es lo que nos permite distinguir un problema de infraestructura de uno de marketing.',
  s3_p2='La asesoría nació de ahí. Llegaban clientes con problemas que no eran de web: un procesador que los dejó fuera, un banco que cerró una cuenta, una función que nadie gestionaba. Responder solo a la parte que encajaba en nuestra lista de servicios no les servía.',
  no_title='Lo que no hacemos',
  no_p1='No somos un procesador de pagos ni un banco. No aprobamos cuentas de comercio ni abrimos cuentas bancarias, y no podemos garantizar que un proveedor lo haga. No ofrecemos asesoría legal, fiscal, de inversión ni otra asesoría financiera regulada, y no gestionamos constitución de sociedades, visados ni inmigración.',
  no_p2='Cuando hace falta un especialista con licencia, es exactamente lo que te diremos.',
  facts_title='Empresa',
  facts=[('Entidad legal','Platonaire LLC'),('Base','California, EE. UU.'),('Trabajamos con','EE. UU. e internacional'),
         ('Idiomas','RU · EN · ES · PT · DE'),('Hacemos internamente','Web · E-comm · Publicidad'),('Evaluación inicial','Gratuita')],
  remote='Prodigy LAB es una empresa remota. No tenemos oficina de puertas abiertas y no nos atribuimos ubicaciones que no tenemos.',
  final_eyebrow='Evaluación inicial gratuita',
  final_h2='Describe el problema. Te diremos qué creemos que es en realidad',
  final_lede='Sin coste, sin compromiso y sin necesidad de una llamada. Si tu situación queda fuera de lo que abordamos, te lo diremos en lugar de enviarte una propuesta.',
  final_cta1='Empezar la evaluación', final_cta2='Escríbenos directamente',
  call='Llamar', foot_priv='Política de privacidad',
  foot_legal='Prodigy LAB no es un procesador de pagos, un banco, ni un proveedor con licencia de asesoría legal, fiscal o financiera.',
  nav=[('#problems','Qué resolvemos'),('#how','Cómo funciona'),('#who','Quiénes somos')],
  problems=[
    ('01 — Pagos','Tu procesador dejó de funcionar para ti','Cuentas suspendidas, fondos retenidos, contracargos al alza, o un sector que tu proveedor actual discretamente no quiere.',['Cuenta cerrada o en revisión','Alto índice de contracargos','Suscripción o modelo de alto riesgo','Necesita redundancia u otras vías']),
    ('02 — Banca','Una banca que no encaja con tu operativa','Sobre todo con empresa en EE. UU. y fundador en el extranjero, o un banco que ya no encaja con el modelo.',['Cuenta congelada o cerrada','Fundador extranjero, entidad en EE. UU.','Abrir cuenta desde el extranjero','Necesita infraestructura alternativa']),
    ('03 — Crecimiento','Tráfico y gasto que no se convierten en ingresos','La captación funciona sobre el papel y falla en la práctica — normalmente en un punto concreto, no en todos.',['Clics sin pedidos','Coste por cliente al alza','Un paso concreto del embudo que falla']),
    ('04 — Operaciones','Trabajo que depende de que alguien se acuerde','Consultas en cuatro bandejas, un CRM en el que nadie confía, informes montados a mano el domingo.',['Sistemas fragmentados','Procesos manuales y repetitivos','Nadie responsable de la parte digital']),
    ('05 — Infraestructura','Funciones demasiado pequeñas para contratar, demasiado caras para ignorar','Logística, nóminas, seguridad, herramientas: necesarias, recurrentes y rara vez justifican un sueldo completo.',['Fulfilment y 3PL','Nóminas y RR. HH.','Seguridad y cumplimiento']),
    ('06 — Presencia digital','El escaparate por el que realmente te juzgan','Sitio web e infraestructura de e-commerce: lo que llevamos años construyendo y seguimos haciendo nosotros.',['Rehacer sitio o tienda','Conversión y checkout','Infraestructura de e-commerce']),
  ],
  steps=[
    ('Cuéntanos qué no funciona','Un cuestionario breve y estructurado, no un formulario de contacto. Qué hace el negocio, qué se rompió, qué has probado ya y cuánta urgencia hay.'),
    ('Lo evaluamos sin coste','Volvemos con lo que creemos que es la restricción real, si merece resolverse ahora y qué caminos realistas existen. Si no nos corresponde, lo decimos.'),
    ('Lo resolvemos o lo derivamos','Lo que está dentro de nuestra competencia lo hacemos nosotros. El resto va a un socio especializado verificado — y sabes de antemano cuál es cuál.'),
  ],
)

L['pt'] = dict(
  scan_secondary='Verificar o site com IA',
  locale='pt_BR', home='/pt/', scan_lang='pt',
  title='Prodigy LAB — Consultoria e Soluções de Negócio',
  desc='As empresas nos procuram com um problema, não para contratar um serviço. Identificamos para onde o dinheiro está indo e resolvemos nós mesmos ou trazemos um parceiro especializado verificado.',
  eyebrow='Business Advisory & Solutions',
  h1='Algo no seu negócio está custando dinheiro. Normalmente não onde você imagina',
  lede='O dono geralmente conhece o sintoma: pagamentos bloqueados, anúncios que não se pagam, contatos perdidos entre canais. Falta uma leitura externa sobre qual desses problemas é o mais caro agora e o que corrigir primeiro.',
  cta1='Conte o que não está funcionando', cta2='O que resolvemos',
  note='Avaliação inicial gratuita · sem compromisso · sem chamada obrigatória',
  quote='Você não precisa de mais um fornecedor. Primeiro precisa de uma leitura honesta do negócio.',
  photo_alt='Aleksandr, fundador da Prodigy LAB',
  s1_eyebrow='O que trava o seu negócio',
  s1_h2='Seis lugares onde empresas estabelecidas perdem dinheiro em silêncio',
  s1_lede='Atuamos nos seis. Alguns resolvemos diretamente, outros por meio de um parceiro especializado que verificamos — e dizemos qual é qual antes de você assumir qualquer compromisso.',
  s2_eyebrow='Como funciona',
  s2_h2='Você recebe o diagnóstico antes que alguém proponha trabalho',
  s3_eyebrow='Quem somos',
  s3_h2='Uma empresa que opera, não um diretório de links',
  s3_p1='A Prodigy LAB passou anos construindo e consertando aquilo por onde as empresas vendem: lojas, sites, publicidade, conversão, conversas com clientes. Esse trabalho continua, e é o que nos permite distinguir um problema de infraestrutura de um de marketing.',
  s3_p2='A consultoria nasceu daí. Clientes chegavam com problemas que não eram de web: um processador que os cortou, um banco que fechou a conta, uma função que ninguém conduzia. Responder só à parte que cabia na nossa lista de serviços não ajudava.',
  no_title='O que não fazemos',
  no_p1='Não somos processadora de pagamentos nem banco. Não aprovamos contas de comerciante nem abrimos contas bancárias, e não podemos garantir que um provedor o faça. Não prestamos consultoria jurídica, tributária, de investimentos ou outra consultoria financeira regulada, e não cuidamos de abertura de empresas, vistos ou imigração.',
  no_p2='Quando é preciso um especialista licenciado, é exatamente isso que diremos.',
  facts_title='Empresa',
  facts=[('Entidade legal','Platonaire LLC'),('Base','Califórnia, EUA'),('Atendemos','EUA e internacional'),
         ('Idiomas','RU · EN · ES · PT · DE'),('Fazemos internamente','Web · E-comm · Anúncios'),('Avaliação inicial','Gratuita')],
  remote='A Prodigy LAB é uma empresa remota. Não mantemos escritório de atendimento e não reivindicamos localizações que não temos.',
  final_eyebrow='Avaliação inicial gratuita',
  final_h2='Descreva o problema. Diremos o que achamos que ele realmente é',
  final_lede='Sem custo, sem compromisso e sem necessidade de chamada. Se a sua situação estiver fora do que atendemos, você será informado disso em vez de receber uma proposta.',
  final_cta1='Começar a avaliação', final_cta2='Fale conosco direto',
  call='Ligar', foot_priv='Política de privacidade',
  foot_legal='A Prodigy LAB não é processadora de pagamentos, banco, nem prestadora licenciada de consultoria jurídica, tributária ou financeira.',
  nav=[('#problems','O que resolvemos'),('#how','Como funciona'),('#who','Quem somos')],
  problems=[
    ('01 — Pagamentos','Seu processador deixou de servir','Contas suspensas, valores retidos, chargebacks subindo, ou um setor que o provedor atual discretamente não quer.',['Conta encerrada ou em análise','Alto índice de chargebacks','Assinatura ou modelo de alto risco','Precisa de redundância ou outras vias']),
    ('02 — Bancos','Um banco que não combina com a sua operação','Especialmente com empresa nos EUA e sócio no exterior, ou um banco que já não serve ao modelo.',['Conta bloqueada ou encerrada','Sócio estrangeiro, empresa nos EUA','Abrir conta a partir do exterior','Precisa de infraestrutura alternativa']),
    ('03 — Crescimento','Tráfego e verba que não viram receita','A aquisição funciona no papel e falha na prática — normalmente num ponto específico, não em tudo.',['Cliques sem pedidos','Custo por cliente subindo','Uma etapa conhecida do funil travando']),
    ('04 — Operações','Trabalho que depende de alguém lembrar','Contatos em quatro caixas, um CRM em que ninguém confia, relatório montado à mão no domingo.',['Sistemas fragmentados','Processos manuais e repetitivos','Ninguém responsável pela parte digital']),
    ('05 — Infraestrutura','Funções pequenas demais para contratar, caras demais para ignorar','Logística, folha, segurança, ferramentas: necessárias, recorrentes e raramente justificam um salário.',['Fulfilment e 3PL','Folha e RH','Segurança e compliance']),
    ('06 — Presença digital','A vitrine pela qual você é realmente julgado','Site e infraestrutura de e-commerce: a parte que construímos há anos e seguimos fazendo.',['Refazer site ou loja','Conversão e checkout','Infraestrutura de e-commerce']),
  ],
  steps=[
    ('Conte o que não está funcionando','Um questionário curto e estruturado, não um formulário de contato. O que o negócio faz, o que quebrou, o que já tentou e qual a urgência.'),
    ('Avaliamos sem custo','Voltamos com o que achamos ser a restrição real, se vale resolver agora e quais são os caminhos realistas. Se não for conosco, dizemos.'),
    ('Resolvemos ou encaminhamos','O que está na nossa competência fazemos nós. O resto vai para um parceiro especializado que verificamos — e você sabe de antemão qual é qual.'),
  ],
)

L['de'] = dict(
  scan_secondary='Website mit KI prüfen',
  locale='de_DE', home='/de/', scan_lang='de',
  title='Prodigy LAB — Business Advisory & Solutions',
  desc='Unternehmen kommen mit einem Problem zu uns, nicht mit einer Dienstleistungsanfrage. Wir finden heraus, wo das Geld tatsächlich verloren geht, und lösen es selbst oder holen einen geprüften Fachpartner dazu.',
  eyebrow='Business Advisory & Solutions',
  h1='Irgendwo in Ihrem Unternehmen versickert Geld. Meist nicht dort, wo Sie es vermuten',
  lede='Inhaber kennen in der Regel das Symptom: Zahlungen blockiert, Werbung rechnet sich nicht, Anfragen gehen zwischen Kanälen verloren. Was fehlt, ist ein Blick von außen darauf, welches dieser Probleme gerade am teuersten ist und was zuerst behoben gehört.',
  cta1='Sagen Sie uns, was nicht funktioniert', cta2='Was wir bearbeiten',
  note='Kostenlose Erstanalyse · unverbindlich · kein Pflichtgespräch',
  quote='Sie brauchen keinen weiteren Dienstleister. Zuerst brauchen Sie eine ehrliche Analyse des Geschäfts.',
  photo_alt='Aleksandr, Gründer von Prodigy LAB',
  s1_eyebrow='Was Ihr Unternehmen ausbremst',
  s1_h2='Sechs Stellen, an denen etablierte Unternehmen still Geld verlieren',
  s1_lede='Wir arbeiten an allen sechs. Manches lösen wir direkt, anderes über einen geprüften Fachpartner — und wir sagen Ihnen vorher, was wovon ist.',
  s2_eyebrow='So läuft es ab',
  s2_h2='Sie bekommen die Analyse, bevor irgendjemand Arbeit vorschlägt',
  s3_eyebrow='Wer wir sind',
  s3_h2='Ein operatives Unternehmen, kein Linkverzeichnis',
  s3_p1='Prodigy LAB hat jahrelang das gebaut und repariert, worüber Unternehmen verkaufen: Shops, Websites, Werbung, Conversion, Kundenkommunikation. Diese Arbeit läuft weiter — und genau deshalb können wir ein Infrastrukturproblem von einem Marketingproblem unterscheiden.',
  s3_p2='Die Beratung ist daraus gewachsen. Kunden kamen mit Problemen, die gar keine Web-Probleme waren: ein Prozessor, der sie fallen ließ, eine Bank, die das Konto schloss, eine Funktion, für die sich niemand zuständig fühlte. Nur den Teil zu beantworten, der in unsere Leistungsliste passte, half ihnen nicht.',
  no_title='Was wir nicht tun',
  no_p1='Wir sind kein Zahlungsdienstleister und keine Bank. Wir genehmigen keine Händlerkonten und eröffnen keine Bankkonten, und wir können nicht garantieren, dass ein Anbieter das tut. Wir erbringen keine Rechts-, Steuer-, Anlage- oder sonstige regulierte Finanzberatung und übernehmen keine Firmengründung, Visa oder Einwanderung.',
  no_p2='Wo ein lizenzierter Fachmann nötig ist, sagen wir genau das.',
  facts_title='Unternehmen',
  facts=[('Rechtsträger','Platonaire LLC'),('Sitz','Kalifornien, USA'),('Arbeitet mit','USA & international'),
         ('Sprachen','RU · EN · ES · PT · DE'),('Intern gebaut','Web · E-Comm · Werbung'),('Erstanalyse','Kostenlos')],
  remote='Prodigy LAB arbeitet remote. Wir unterhalten kein Ladenbüro und beanspruchen keine Standorte, die wir nicht haben.',
  final_eyebrow='Kostenlose Erstanalyse',
  final_h2='Beschreiben Sie das Problem. Wir sagen Ihnen, was es aus unserer Sicht wirklich ist',
  final_lede='Kostenlos, unverbindlich und ohne Pflicht zu einem Gespräch. Liegt Ihre Situation außerhalb unseres Bereichs, erfahren Sie das — statt ein Angebot zu bekommen.',
  final_cta1='Analyse starten', final_cta2='Direkt schreiben',
  call='Anrufen', foot_priv='Datenschutz',
  foot_legal='Prodigy LAB ist kein Zahlungsdienstleister, keine Bank und kein lizenzierter Anbieter von Rechts-, Steuer- oder Finanzberatung.',
  nav=[('#problems','Was wir lösen'),('#how','Ablauf'),('#who','Wer wir sind')],
  problems=[
    ('01 — Zahlungen','Ihr Prozessor passt nicht mehr zu Ihnen','Konten gesperrt, Gelder einbehalten, steigende Chargebacks — oder eine Branche, die Ihr Anbieter still nicht will.',['Konto geschlossen oder in Prüfung','Hohe Chargeback-Quote','Abo- oder High-Risk-Modell','Braucht Redundanz oder andere Wege']),
    ('02 — Banking','Banking, das nicht zu Ihrem Betrieb passt','Besonders bei US-Firma mit Gründer im Ausland oder wenn die Bank nicht mehr zum Modell passt.',['Konto eingefroren oder geschlossen','Ausländischer Gründer, US-Gesellschaft','Kontoeröffnung aus dem Ausland','Braucht alternative Infrastruktur']),
    ('03 — Wachstum','Traffic und Budget, die keinen Umsatz ergeben','Die Akquise funktioniert auf dem Papier und scheitert in der Praxis — meist an einer Stelle, nicht überall.',['Klicks ohne Bestellungen','Steigende Kundenkosten','Ein konkreter Funnel-Schritt schwächelt']),
    ('04 — Betrieb','Arbeit, die daran hängt, dass sich jemand erinnert','Anfragen in vier Postfächern, ein CRM, dem niemand traut, Reporting sonntags von Hand.',['Zersplitterte Systeme','Manuelle, wiederkehrende Abläufe','Niemand verantwortet das Digitale']),
    ('05 — Infrastruktur','Funktionen, für die sich eine Stelle nicht lohnt','Fulfilment, Lohn, Sicherheit, Tools: nötig, wiederkehrend und selten eine volle Stelle wert.',['Fulfilment und 3PL','Lohn und HR','Sicherheit und Compliance']),
    ('06 — Digitale Präsenz','Das Schaufenster, nach dem Sie beurteilt werden','Website und E-Commerce-Infrastruktur: das, was wir seit Jahren selbst bauen.',['Website oder Shop neu aufbauen','Conversion und Checkout','E-Commerce-Infrastruktur']),
  ],
  steps=[
    ('Sagen Sie, was nicht funktioniert','Eine kurze strukturierte Aufnahme, kein Kontaktformular. Was das Geschäft macht, was kaputt ist, was Sie schon versucht haben und wie dringend es ist.'),
    ('Wir analysieren — kostenlos','Wir melden uns mit dem, was wir für die eigentliche Engstelle halten, ob sich das jetzt lohnt und welche realistischen Wege es gibt. Ist es nicht unser Thema, sagen wir das.'),
    ('Wir lösen es oder leiten weiter','Was in unserer Kompetenz liegt, machen wir selbst. Alles andere geht an einen geprüften Fachpartner — und Sie wissen vorher, was wovon ist.'),
  ],
)
