# -*- coding: utf-8 -*-
"""Контент новой главной. Один источник — пять языков.
Позиционирование: Business Advisory & Solutions (бриф 25.09.2026)."""

PHONE_HREF = "tel:+18182690416"
PHONE_TEXT = "+1 (818) 269-0416"
WA = "https://wa.me/18182690416"
DIAG = "https://scan.prodigylab.studio/diagnostic?lang="
SCAN = "https://scan.prodigylab.studio/scan?lang="

L = {}

L['ru'] = dict(
  cases_eyebrow='Доказательства',
  cases_h2='Кому уже собирали',
  cases_lede='Магазины и бизнесы, которые мы строили и ведём сами. Это же и есть ответ на вопрос, откуда мы знаем, как устроена операционная часть.',
  cases_cta='Смотреть разборы',
  banner_ask='Предпочитаете {lang}? Открыть версию на этом языке',
  banner_open='Открыть',
  banner_stay='Остаться на русском',
  lang_names=('английский', 'русский', 'испанский', 'португальский', 'немецкий'),
  scan_secondary='Проверить сайт с помощью AI',
  locale='ru_RU', home='/ru/', scan_lang='ru',
  title='Prodigy LAB — разбор и решение бизнес-задач',
  desc='Бизнес приходит к нам с проблемой, а не за услугой. Мы определяем, где именно теряются деньги, и либо решаем сами, либо подключаем проверенного профильного партнёра.',
  eyebrow='Business Advisory & Solutions',
  h1='Где-то в вашем бизнесе утекают деньги. Чаще всего — не там, где кажется',
  lede='Владелец обычно знает симптом: платежи заблокировали, реклама не окупается, заявки теряются между каналами. Чего нет — взгляда со стороны на то, какая из этих проблем сейчас самая дорогая и что чинить первым.',
  cta1='Расскажите, что не работает', cta2='Что мы разбираем',
  note='Первичный разбор бесплатно · без обязательств · без обязательного созвона',
  quote='Вам не нужен ещё один подрядчик. Сначала нужен честный разбор бизнеса.',
  photo_alt='Александр, основатель Prodigy LAB',
  s1_eyebrow='Что мешает бизнесу расти',
  s1_h2='Девять мест, где бизнес обычно и ломается',
  s1_lede='Часть мы решаем сами, часть — через специалиста, которого проверили. И говорим, что из этого что, до того как вы на что-то соглашаетесь.',
  s2_eyebrow='Как это устроено',
  s2_h2='Сначала вы получаете разбор — и только потом кто-то предлагает работу',
  s3_eyebrow='Кто мы',
  s3_h2='Компания, которая сама всё это строила, а не каталог ссылок',
  s3_p1='Prodigy LAB годами собирал и чинил то, через что бизнес продаёт: магазины, сайты, рекламу, конверсию, переписку с клиентами. Эта работа никуда не делась — и именно она позволяет отличить проблему инфраструктуры от проблемы маркетинга.',
  s3_p2='Консалтинг вырос из неё. Клиенты приходили с задачами, которые вообще не про сайт: процессор отключил приём платежей, банк закрыл счёт, функцию в компании никто не ведёт. Отвечать только на ту часть, что попадает в наш прайс-лист, было бесполезно.',
  no_title='Чего мы не делаем',
  no_p1='Мы не платёжный процессор и не банк. Мы не одобряем merchant-аккаунты и не открываем счета, и не можем гарантировать, что это сделает провайдер. Мы не оказываем юридических, налоговых, инвестиционных и иных регулируемых финансовых консультаций и не занимаемся регистрацией юрлиц, визами и иммиграцией.',
  no_p2='Если задача требует лицензированного специалиста — мы так и скажем.',
  facts_title='Компания',
  facts=[('Юрлицо','Platonaire LLC'),('База','Калифорния, США'),('Работаем с','США и международно'),
         ('Языки','RU · EN · ES · PT · DE'),('Делаем сами','Сайты · E-comm · Реклама'),('Первичный разбор','Бесплатно')],
  remote='Prodigy LAB работает удалённо. Офиса, куда можно приехать, у нас нет, и мы не приписываем себе городов, в которых не присутствуем.',
  final_eyebrow='Бесплатный первичный разбор',
  final_h2='Опишите проблему. Мы скажем, в чём она, по нашему мнению, на самом деле',
  final_lede='Бесплатно, ни к чему не обязывает, созвон необязателен. Если ваша ситуация вне того, чем мы занимаемся, вы получите об этом честный ответ, а не коммерческое предложение.',
  final_cta1='Начать разбор', final_cta2='Написать напрямую',
  call='Позвонить', foot_priv='Политика конфиденциальности',
  foot_legal='Prodigy LAB не является платёжным процессором, банком или лицензированным поставщиком юридических, налоговых или финансовых консультаций.',
  nav=[('#problems','Что разбираем'),('#how','Как устроено'),('#who','Кто мы')],
  problems=[
    ('01 — Платежи','Приём платежей остановился',
     'Stripe, Square или PayPal закрыли аккаунт, держат выплаты, назначили резерв — или ваша вертикаль им просто не нужна.',
     ['Аккаунт закрыт или заморожен','Выплаты удерживают, назначен резерв','Отказ в merchant account','Высокий процент chargebacks','Нужен запасной процессинг']),
    ('02 — Банкинг','Банк сказал «нет» или закрыл счёт',
     'Особенно если компания в США, а основатель за рубежом, или структура кажется банку сложной.',
     ['Счёт закрыт или ограничен','Отказ по заявке','Иностранный основатель, юрлицо в США','Нужен второй, запасной банк','Мультивалютные и трансграничные расчёты']),
    ('03 — Финансирование','Деньги нужны раньше, чем они придут',
     'Оборотные средства, закупка товара, зарплаты, оборудование — и кассовый разрыв между этим всем.',
     ['Банк отказал в кредите','Разрыв в обороте','Закупка товара или оборудования','Деньги на рост и расширение','Альтернативное финансирование']),
    ('04 — Рост и продажи','Трафик есть, выручки нет',
     'Привлечение работает на бумаге и не работает на практике — обычно ломается в одном месте, а не везде.',
     ['Клики без заказов','Дорогой клиент, слабый ROAS','Заявки есть, продаж нет','Amazon или маркетплейсы не растут','Не получается масштабироваться']),
    ('05 — Операции','Работа держится на том, что кто-то помнит',
     'CRM, автоматизация, передача между маркетингом и продажами — всё живёт в ручном режиме.',
     ['CRM есть, но ей не верят','Ручные повторяющиеся процессы','Системы не связаны между собой','Заявки теряются при передаче','Узкие места в операционке']),
    ('06 — Инфраструктура','Функции, ради которых нанимать дорого',
     'Зарплаты и кадры, безопасность, рабочие ИТ — нужны постоянно и редко окупают отдельную ставку.',
     ['Расчёт зарплат и кадровый учёт','Нет программы безопасности','Риск шифровальщика, нужен аудит','Управляемый ИТ и служба поддержки','Microsoft 365, облако, резервные копии']),
    ('07 — Учёт и налоги','Книги отстали, сроки горят',
     'Бухгалтерия, закрытие месяца, налоги, восстановление учёта — особенно если компания в США, а вы нет.',
     ['Учёт запущен, нужно восстановление','Нет закрытия месяца','Налоговая отчётность просрочена','Налог с продаж по штатам','Нужен финансовый директор на часть ставки']),
    ('08 — Логистика и склад','Вы переросли отгрузку своими силами',
     'Склад, фулфилмент, подготовка к Amazon и Walmart, возвраты, трансграничная доставка.',
     ['Нужен 3PL и склад','Логистика съедает маржу','Подготовка товара к маркетплейсам','Возвраты не обрабатываются','Международная доставка']),
    ('09 — Сайт и e-commerce','Витрина, по которой вас и судят',
     'То, что мы много лет строили и продолжаем делать своими руками.',
     ['Сайт или магазин пора пересобрать','Конверсия и оформление заказа','Аналитика и отслеживание не настроены','Нужен честный разбор сайта','Интеграции и базовая автоматизация']),
  ],
  steps=[
    ('Расскажите, что не работает','Короткая структурированная анкета, а не форма «напишите нам». Чем занимается бизнес, что сломалось, что уже пробовали и насколько это срочно.'),
    ('Мы разбираем — бесплатно','Возвращаемся с тем, что считаем настоящим ограничением, стоит ли это решать сейчас и какие есть реальные пути. Если задача не наша — скажем прямо.'),
    ('Решаем сами или передаём','Что в нашей компетенции — делаем сами. Остальное уходит профильному партнёру, которого мы проверили. Что именно из этого что, вы знаете заранее.'),
  ],
)

L['en'] = dict(
  cases_eyebrow='Proof',
  cases_h2='Who we have built for',
  cases_lede='Stores and businesses we built and still run ourselves. That is also the answer to how we know what the operating side actually looks like.',
  cases_cta='See the case studies',
  banner_ask='Prefer {lang}? Open the {lang} version',
  banner_open='Open',
  banner_stay='Stay in English',
  lang_names=('English', 'Russian', 'Spanish', 'Portuguese', 'German'),
  scan_secondary='Run a free AI website scan',
  locale='en_US', home='/', scan_lang='en',
  title='Prodigy LAB — Business Advisory & Solutions',
  desc='Businesses come to us with a problem, not a service request. We work out where the money is actually going, then either solve it ourselves or bring in a vetted specialist partner.',
  eyebrow='Business Advisory & Solutions',
  h1='Something in your business is costing you money. Usually not where you think',
  lede='Owners normally know the symptom: payments blocked, ads that do not pay back, enquiries lost between channels. What is missing is an outside read on which of those is most expensive right now, and what to fix first.',
  cta1='Tell us what is not working', cta2='What we handle',
  note='Free initial assessment · no obligation · no call required',
  quote='You do not need another contractor. First you need an honest read on the business.',
  photo_alt='Aleksandr, founder of Prodigy LAB',
  s1_eyebrow="What's holding your business back",
  s1_h2='Nine places where a business usually breaks',
  s1_lede='Some of it we solve ourselves, some through a specialist we have vetted. And we tell you which is which before you commit to anything.',
  s2_eyebrow='How it works',
  s2_h2='You get the diagnosis before anyone proposes work',
  s3_eyebrow='Who we are',
  s3_h2='An operating company, not a directory of links',
  s3_p1='Prodigy LAB spent years building and fixing the systems businesses sell through: stores, websites, advertising, conversion, customer conversations. That work continues, and it is what lets us tell an infrastructure problem from a marketing one.',
  s3_p2='Advisory grew out of it. Clients kept arriving with problems that were not web problems at all — a processor that dropped them, a bank that closed an account, a function nobody owned. Answering only the part that fit our service list was not useful to them.',
  no_title='What we do not do',
  no_p1='We are not a payment processor and not a bank. We do not approve merchant accounts or open bank accounts, and we cannot guarantee a provider will. We do not provide legal, tax, investment or other regulated financial advice, and we do not handle company formation, visas or immigration.',
  no_p2='Where a licensed specialist is required, that is exactly what we will tell you.',
  facts_title='Company',
  facts=[('Legal entity','Platonaire LLC'),('Based','California, USA'),('Works with','US & international'),
         ('Languages','RU · EN · ES · PT · DE'),('Built in-house','Web · E-comm · Ads'),('Initial assessment','Free')],
  remote='Prodigy LAB is a remote company. We do not keep a walk-in office, and we do not claim locations we do not have.',
  final_eyebrow='Free initial assessment',
  final_h2='Describe the problem. We will tell you what we think it actually is',
  final_lede='No cost, no obligation, no requirement to get on a call. If your situation is outside what we handle, you will be told that instead of receiving a proposal.',
  final_cta1='Start the assessment', final_cta2='Message us directly',
  call='Call us', foot_priv='Privacy Policy',
  foot_legal='Prodigy LAB is not a payment processor, a bank, or a licensed provider of legal, tax or financial advice.',
  nav=[('#problems','What we solve'),('#how','How it works'),('#who','Who we are')],
  problems=[
    ('01 — Payments','Taking payments has stopped',
     'Stripe, Square or PayPal closed the account, are holding payouts, set a reserve — or your vertical is one they quietly do not want.',
     ['Account closed or frozen','Payouts held, reserve imposed','Merchant account declined','High chargeback ratio','Needs backup processing']),
    ('02 — Banking','The bank said no, or closed the account',
     'Especially with a US company and a founder abroad, or a structure the bank finds complicated.',
     ['Account closed or restricted','Application rejected','Foreign founder, US entity','Needs a second, backup bank','Multi-currency and cross-border']),
    ('03 — Funding','You need the money before it arrives',
     'Working capital, inventory, payroll, equipment — and the cash-flow gap between all of it.',
     ['The bank declined','Cash-flow gap','Inventory or equipment purchase','Capital to expand','Alternative financing']),
    ('04 — Growth','Traffic comes in, revenue does not',
     'Acquisition works on paper and fails in practice — usually in one specific place, not everywhere.',
     ['Clicks without orders','High cost per customer, weak ROAS','Leads that never convert','Amazon or marketplaces stalling','Cannot scale further']),
    ('05 — Operations','Work that depends on someone remembering',
     'CRM, automation, the handoff between marketing and sales — all of it running by hand.',
     ['A CRM nobody trusts','Manual, repeatable processes','Systems that do not talk to each other','Leads lost in the handoff','Operational bottlenecks']),
    ('06 — Infrastructure','Functions too small to hire for',
     'Payroll and HR, security, working IT — necessary, recurring, rarely worth a full salary.',
     ['Payroll and HR compliance','No security program','Ransomware risk, needs assessment','Managed IT and help desk','Microsoft 365, cloud, backups']),
    ('07 — Accounting & tax','The books are behind and deadlines are not',
     'Bookkeeping, monthly close, tax, cleanup — especially when the company is in the US and you are not.',
     ['Books need a cleanup','No monthly close','Tax filing overdue','Sales tax across states','Needs a fractional CFO']),
    ('08 — Fulfilment & logistics','You have outgrown shipping it yourself',
     'Warehousing, fulfilment, Amazon and Walmart prep, returns, cross-border shipping.',
     ['Needs a 3PL and warehousing','Logistics eating the margin','Marketplace prep','Returns not handled','International shipping']),
    ('09 — Website & e-commerce','The storefront you are judged on',
     'The part we have built for years and still build ourselves.',
     ['Site or store needs rebuilding','Conversion and checkout','Tracking and analytics missing','Needs an honest site teardown','Integrations and basic automation']),
  ],
  steps=[
    ('Tell us what is not working','A short structured intake, not a contact form. What the business does, what broke, what you have already tried, and how urgent it is.'),
    ('We assess it — at no cost','We come back with what we think the real constraint is, whether it is worth solving now, and what the realistic paths are. If it is not ours to solve, we say so.'),
    ('We solve it, or route it','Work inside our own competence we do ourselves. Anything else goes to a specialist partner we have checked — and you are told upfront which it is.'),
  ],
)

L['es'] = dict(
  cases_eyebrow='Pruebas',
  cases_h2='Para quién lo hemos hecho',
  cases_lede='Tiendas y negocios que construimos y seguimos gestionando. Esa es también la respuesta a cómo sabemos cómo funciona la parte operativa.',
  cases_cta='Ver los casos',
  banner_ask='¿Prefiere {lang}? Abrir la versión en ese idioma',
  banner_open='Abrir',
  banner_stay='Seguir en español',
  lang_names=('inglés', 'ruso', 'español', 'portugués', 'alemán'),
  scan_secondary='Analizar el sitio con IA',
  locale='es_ES', home='/es/', scan_lang='es',
  title='Prodigy LAB — Asesoría y Soluciones de Negocio',
  desc='Las empresas acuden a nosotros con un problema, no a pedir un servicio. Determinamos dónde se está yendo el dinero y lo resolvemos nosotros o incorporamos a un socio especializado verificado.',
  eyebrow='Business Advisory & Solutions',
  h1='Algo en tu negocio te está costando dinero. Normalmente no donde crees',
  lede='El dueño suele conocer el síntoma: pagos bloqueados, publicidad que no se paga sola, consultas que se pierden entre canales. Lo que falta es una lectura externa de cuál de esos problemas sale más caro ahora y qué arreglar primero.',
  cta1='Cuéntanos qué no funciona', cta2='Qué abordamos',
  note='Evaluación inicial gratuita · sin compromiso · sin llamada obligatoria',
  quote='No necesita otro proveedor. Primero necesita una lectura honesta del negocio.',
  photo_alt='Aleksandr, fundador de Prodigy LAB',
  s1_eyebrow='Qué frena a tu negocio',
  s1_h2='Nueve lugares donde un negocio suele romperse',
  s1_lede='Parte lo resolvemos nosotros, parte con un especialista verificado. Y le decimos cuál es cuál antes de que se comprometa.',
  s2_eyebrow='Cómo funciona',
  s2_h2='Primero recibes el diagnóstico y solo después alguien propone trabajo',
  s3_eyebrow='Quiénes somos',
  s3_h2='Una empresa operativa, no un directorio de enlaces',
  s3_p1='Prodigy LAB lleva años construyendo y arreglando aquello con lo que las empresas venden: tiendas, sitios web, publicidad, conversión, conversaciones con clientes. Ese trabajo continúa, y es lo que nos permite distinguir un problema de infraestructura de uno de marketing.',
  s3_p2='La asesoría nació de ahí. Llegaban clientes con problemas que no eran de web: un procesador que los dejó fuera, un banco que cerró una cuenta, una función que nadie gestionaba. Responder solo a la parte que encajaba en nuestra lista de servicios no les servía.',
  no_title='Lo que no hacemos',
  no_p1='No somos un procesador de pagos ni un banco. No aprobamos cuentas de comercio ni abrimos cuentas bancarias, y no podemos garantizar que un proveedor lo haga. No ofrecemos asesoría legal, fiscal, de inversión ni otra asesoría financiera regulada, y no gestionamos constitución de sociedades, visados ni inmigración.',
  no_p2='Cuando hace falta un especialista con licencia, es exactamente lo que te diremos.',
  facts_title='Empresa',
  facts=[('Entidad legal','Platonaire LLC'),('Base','California, EE. UU.'),('Trabajamos con','EE. UU. e internacional'),
         ('Idiomas','RU · EN · ES · PT · DE'),('Hacemos internamente','Web · E-comm · Publicidad'),('Evaluación inicial','Gratuita')],
  remote='Prodigy LAB es una empresa remota. No tenemos oficina de puertas abiertas y no nos atribuimos ubicaciones que no tenemos.',
  final_eyebrow='Evaluación inicial gratuita',
  final_h2='Describe el problema. Te diremos qué creemos que es en realidad',
  final_lede='Sin coste, sin compromiso y sin necesidad de una llamada. Si tu situación queda fuera de lo que abordamos, te lo diremos en lugar de enviarte una propuesta.',
  final_cta1='Empezar la evaluación', final_cta2='Escríbenos directamente',
  call='Llamar', foot_priv='Política de privacidad',
  foot_legal='Prodigy LAB no es un procesador de pagos, un banco, ni un proveedor con licencia de asesoría legal, fiscal o financiera.',
  nav=[('#problems','Qué resolvemos'),('#how','Cómo funciona'),('#who','Quiénes somos')],
  problems=[
    ('01 — Pagos','El cobro de pagos se detuvo',
     'Stripe, Square o PayPal cerraron la cuenta, retienen los pagos, impusieron una reserva — o su sector no les interesa.',
     ['Cuenta cerrada o congelada','Pagos retenidos, reserva impuesta','Cuenta de comercio rechazada','Alto índice de contracargos','Necesita procesamiento de respaldo']),
    ('02 — Banca','El banco dijo no o cerró la cuenta',
     'Sobre todo con empresa en EE. UU. y fundador en el extranjero, o una estructura que al banco le parece compleja.',
     ['Cuenta cerrada o restringida','Solicitud rechazada','Fundador extranjero, entidad en EE. UU.','Necesita un segundo banco','Multidivisa y transfronterizo']),
    ('03 — Financiación','Necesita el dinero antes de que llegue',
     'Capital de trabajo, inventario, nóminas, equipamiento — y el desfase de caja entre todo eso.',
     ['El banco denegó el crédito','Desfase de caja','Compra de inventario o equipo','Capital para crecer','Financiación alternativa']),
    ('04 — Crecimiento','Entra tráfico, no entran ingresos',
     'La captación funciona sobre el papel y falla en la práctica, normalmente en un punto concreto.',
     ['Clics sin pedidos','Coste por cliente alto, ROAS débil','Contactos que no convierten','Amazon o marketplaces estancados','No consigue escalar']),
    ('05 — Operaciones','Trabajo que depende de que alguien recuerde',
     'CRM, automatización, el traspaso entre marketing y ventas: todo a mano.',
     ['Un CRM en el que nadie confía','Procesos manuales repetitivos','Sistemas que no se comunican','Contactos perdidos en el traspaso','Cuellos de botella operativos']),
    ('06 — Infraestructura','Funciones demasiado pequeñas para contratar',
     'Nóminas y RR. HH., seguridad, IT operativo: necesarios y recurrentes.',
     ['Nóminas y cumplimiento laboral','Sin programa de seguridad','Riesgo de ransomware, hace falta evaluación','IT gestionado y soporte','Microsoft 365, nube, copias']),
    ('07 — Contabilidad e impuestos','Los libros van atrasados y los plazos no',
     'Contabilidad, cierre mensual, impuestos, puesta al día — sobre todo si la empresa está en EE. UU. y usted no.',
     ['Los libros necesitan puesta al día','Sin cierre mensual','Declaraciones vencidas','Impuesto sobre ventas por estados','Necesita un CFO a tiempo parcial']),
    ('08 — Logística y almacén','Ha superado el envío por su cuenta',
     'Almacén, fulfilment, preparación para Amazon y Walmart, devoluciones, envío internacional.',
     ['Necesita 3PL y almacén','La logística se come el margen','Preparación para marketplaces','Devoluciones sin gestionar','Envío internacional']),
    ('09 — Sitio y e-commerce','El escaparate por el que le juzgan',
     'La parte que llevamos años construyendo y seguimos haciendo nosotros.',
     ['Hay que rehacer el sitio o la tienda','Conversión y checkout','Falta medición y analítica','Necesita un análisis honesto del sitio','Integraciones y automatización básica']),
  ],
  steps=[
    ('Cuéntanos qué no funciona','Un cuestionario breve y estructurado, no un formulario de contacto. Qué hace el negocio, qué se rompió, qué has probado ya y cuánta urgencia hay.'),
    ('Lo evaluamos sin coste','Volvemos con lo que creemos que es la restricción real, si merece resolverse ahora y qué caminos realistas existen. Si no nos corresponde, lo decimos.'),
    ('Lo resolvemos o lo derivamos','Lo que está dentro de nuestra competencia lo hacemos nosotros. El resto va a un socio especializado verificado — y sabes de antemano cuál es cuál.'),
  ],
)

L['pt'] = dict(
  cases_eyebrow='Provas',
  cases_h2='Para quem já construímos',
  cases_lede='Lojas e negócios que construímos e continuamos tocando. Essa é também a resposta de como sabemos como funciona a parte operacional.',
  cases_cta='Ver os casos',
  banner_ask='Prefere {lang}? Abrir a versão nesse idioma',
  banner_open='Abrir',
  banner_stay='Continuar em português',
  lang_names=('inglês', 'russo', 'espanhol', 'português', 'alemão'),
  scan_secondary='Verificar o site com IA',
  locale='pt_BR', home='/pt/', scan_lang='pt',
  title='Prodigy LAB — Consultoria e Soluções de Negócio',
  desc='As empresas nos procuram com um problema, não para contratar um serviço. Identificamos para onde o dinheiro está indo e resolvemos nós mesmos ou trazemos um parceiro especializado verificado.',
  eyebrow='Business Advisory & Solutions',
  h1='Algo no seu negócio está custando dinheiro. Normalmente não onde você imagina',
  lede='O dono geralmente conhece o sintoma: pagamentos bloqueados, anúncios que não se pagam, contatos perdidos entre canais. Falta uma leitura externa sobre qual desses problemas é o mais caro agora e o que corrigir primeiro.',
  cta1='Conte o que não está funcionando', cta2='O que resolvemos',
  note='Avaliação inicial gratuita · sem compromisso · sem chamada obrigatória',
  quote='Você não precisa de mais um fornecedor. Primeiro precisa de uma leitura honesta do negócio.',
  photo_alt='Aleksandr, fundador da Prodigy LAB',
  s1_eyebrow='O que trava o seu negócio',
  s1_h2='Nove lugares onde um negócio costuma quebrar',
  s1_lede='Parte resolvemos nós, parte com um especialista verificado. E dizemos qual é qual antes de você assumir qualquer compromisso.',
  s2_eyebrow='Como funciona',
  s2_h2='Você recebe o diagnóstico antes que alguém proponha trabalho',
  s3_eyebrow='Quem somos',
  s3_h2='Uma empresa que opera, não um diretório de links',
  s3_p1='A Prodigy LAB passou anos construindo e consertando aquilo por onde as empresas vendem: lojas, sites, publicidade, conversão, conversas com clientes. Esse trabalho continua, e é o que nos permite distinguir um problema de infraestrutura de um de marketing.',
  s3_p2='A consultoria nasceu daí. Clientes chegavam com problemas que não eram de web: um processador que os cortou, um banco que fechou a conta, uma função que ninguém conduzia. Responder só à parte que cabia na nossa lista de serviços não ajudava.',
  no_title='O que não fazemos',
  no_p1='Não somos processadora de pagamentos nem banco. Não aprovamos contas de comerciante nem abrimos contas bancárias, e não podemos garantir que um provedor o faça. Não prestamos consultoria jurídica, tributária, de investimentos ou outra consultoria financeira regulada, e não cuidamos de abertura de empresas, vistos ou imigração.',
  no_p2='Quando é preciso um especialista licenciado, é exatamente isso que diremos.',
  facts_title='Empresa',
  facts=[('Entidade legal','Platonaire LLC'),('Base','Califórnia, EUA'),('Atendemos','EUA e internacional'),
         ('Idiomas','RU · EN · ES · PT · DE'),('Fazemos internamente','Web · E-comm · Anúncios'),('Avaliação inicial','Gratuita')],
  remote='A Prodigy LAB é uma empresa remota. Não mantemos escritório de atendimento e não reivindicamos localizações que não temos.',
  final_eyebrow='Avaliação inicial gratuita',
  final_h2='Descreva o problema. Diremos o que achamos que ele realmente é',
  final_lede='Sem custo, sem compromisso e sem necessidade de chamada. Se a sua situação estiver fora do que atendemos, você será informado disso em vez de receber uma proposta.',
  final_cta1='Começar a avaliação', final_cta2='Fale conosco direto',
  call='Ligar', foot_priv='Política de privacidade',
  foot_legal='A Prodigy LAB não é processadora de pagamentos, banco, nem prestadora licenciada de consultoria jurídica, tributária ou financeira.',
  nav=[('#problems','O que resolvemos'),('#how','Como funciona'),('#who','Quem somos')],
  problems=[
    ('01 — Pagamentos','O recebimento de pagamentos parou',
     'Stripe, Square ou PayPal encerraram a conta, retêm repasses, impuseram reserva — ou o seu setor não interessa a eles.',
     ['Conta encerrada ou congelada','Repasses retidos, reserva imposta','Conta de comerciante recusada','Alto índice de chargebacks','Precisa de processamento reserva']),
    ('02 — Bancos','O banco disse não ou encerrou a conta',
     'Especialmente com empresa nos EUA e sócio no exterior, ou uma estrutura que o banco acha complexa.',
     ['Conta encerrada ou restrita','Pedido recusado','Sócio estrangeiro, empresa nos EUA','Precisa de um segundo banco','Multimoeda e transfronteiriço']),
    ('03 — Capital','Precisa do dinheiro antes que ele chegue',
     'Capital de giro, estoque, folha, equipamentos — e o descompasso de caixa entre tudo isso.',
     ['O banco negou o crédito','Descompasso de caixa','Compra de estoque ou equipamento','Capital para crescer','Financiamento alternativo']),
    ('04 — Crescimento','Entra tráfego, não entra receita',
     'A aquisição funciona no papel e falha na prática, normalmente num ponto específico.',
     ['Cliques sem pedidos','Custo por cliente alto, ROAS fraco','Contatos que não convertem','Amazon ou marketplaces travados','Não consegue escalar']),
    ('05 — Operações','Trabalho que depende de alguém lembrar',
     'CRM, automação, a passagem entre marketing e vendas: tudo no braço.',
     ['Um CRM em que ninguém confia','Processos manuais repetitivos','Sistemas que não conversam','Contatos perdidos na passagem','Gargalos operacionais']),
    ('06 — Infraestrutura','Funções pequenas demais para contratar',
     'Folha e RH, segurança, TI operacional: necessários e recorrentes.',
     ['Folha e conformidade trabalhista','Sem programa de segurança','Risco de ransomware, precisa de avaliação','TI gerenciada e suporte','Microsoft 365, nuvem, backups']),
    ('07 — Contabilidade e impostos','Os livros atrasaram e os prazos não',
     'Contabilidade, fechamento mensal, impostos, regularização — sobretudo se a empresa está nos EUA e você não.',
     ['Livros precisam de regularização','Sem fechamento mensal','Declarações vencidas','Imposto sobre vendas por estado','Precisa de um CFO parcial']),
    ('08 — Logística e armazém','Você superou o envio por conta própria',
     'Armazém, fulfilment, preparação para Amazon e Walmart, devoluções, envio internacional.',
     ['Precisa de 3PL e armazém','A logística come a margem','Preparação para marketplaces','Devoluções sem tratamento','Envio internacional']),
    ('09 — Site e e-commerce','A vitrine pela qual você é julgado',
     'A parte que construímos há anos e seguimos fazendo nós mesmos.',
     ['Site ou loja precisa ser refeito','Conversão e checkout','Falta mensuração e analytics','Precisa de uma análise honesta do site','Integrações e automação básica']),
  ],
  steps=[
    ('Conte o que não está funcionando','Um questionário curto e estruturado, não um formulário de contato. O que o negócio faz, o que quebrou, o que já tentou e qual a urgência.'),
    ('Avaliamos sem custo','Voltamos com o que achamos ser a restrição real, se vale resolver agora e quais são os caminhos realistas. Se não for conosco, dizemos.'),
    ('Resolvemos ou encaminhamos','O que está na nossa competência fazemos nós. O resto vai para um parceiro especializado que verificamos — e você sabe de antemão qual é qual.'),
  ],
)

L['de'] = dict(
  cases_eyebrow='Belege',
  cases_h2='Für wen wir gebaut haben',
  cases_lede='Shops und Unternehmen, die wir gebaut haben und weiterhin selbst betreuen. Das ist zugleich die Antwort darauf, woher wir wissen, wie der operative Teil wirklich aussieht.',
  cases_cta='Fallbeispiele ansehen',
  banner_ask='Bevorzugen Sie {lang}? Version in dieser Sprache öffnen',
  banner_open='Öffnen',
  banner_stay='Auf Deutsch bleiben',
  lang_names=('Englisch', 'Russisch', 'Spanisch', 'Portugiesisch', 'Deutsch'),
  scan_secondary='Website mit KI prüfen',
  locale='de_DE', home='/de/', scan_lang='de',
  title='Prodigy LAB — Business Advisory & Solutions',
  desc='Unternehmen kommen mit einem Problem zu uns, nicht mit einer Dienstleistungsanfrage. Wir finden heraus, wo das Geld tatsächlich verloren geht, und lösen es selbst oder holen einen geprüften Fachpartner dazu.',
  eyebrow='Business Advisory & Solutions',
  h1='Irgendwo in Ihrem Unternehmen versickert Geld. Meist nicht dort, wo Sie es vermuten',
  lede='Inhaber kennen in der Regel das Symptom: Zahlungen blockiert, Werbung rechnet sich nicht, Anfragen gehen zwischen Kanälen verloren. Was fehlt, ist ein Blick von außen darauf, welches dieser Probleme gerade am teuersten ist und was zuerst behoben gehört.',
  cta1='Sagen Sie uns, was nicht funktioniert', cta2='Was wir bearbeiten',
  note='Kostenlose Erstanalyse · unverbindlich · kein Pflichtgespräch',
  quote='Sie brauchen keinen weiteren Dienstleister. Zuerst brauchen Sie eine ehrliche Analyse des Geschäfts.',
  photo_alt='Aleksandr, Gründer von Prodigy LAB',
  s1_eyebrow='Was Ihr Unternehmen ausbremst',
  s1_h2='Neun Stellen, an denen ein Unternehmen meist bricht',
  s1_lede='Manches lösen wir selbst, anderes über einen geprüften Fachmann. Und wir sagen Ihnen vorher, was wovon ist.',
  s2_eyebrow='So läuft es ab',
  s2_h2='Sie bekommen die Analyse, bevor irgendjemand Arbeit vorschlägt',
  s3_eyebrow='Wer wir sind',
  s3_h2='Ein operatives Unternehmen, kein Linkverzeichnis',
  s3_p1='Prodigy LAB hat jahrelang das gebaut und repariert, worüber Unternehmen verkaufen: Shops, Websites, Werbung, Conversion, Kundenkommunikation. Diese Arbeit läuft weiter — und genau deshalb können wir ein Infrastrukturproblem von einem Marketingproblem unterscheiden.',
  s3_p2='Die Beratung ist daraus gewachsen. Kunden kamen mit Problemen, die gar keine Web-Probleme waren: ein Prozessor, der sie fallen ließ, eine Bank, die das Konto schloss, eine Funktion, für die sich niemand zuständig fühlte. Nur den Teil zu beantworten, der in unsere Leistungsliste passte, half ihnen nicht.',
  no_title='Was wir nicht tun',
  no_p1='Wir sind kein Zahlungsdienstleister und keine Bank. Wir genehmigen keine Händlerkonten und eröffnen keine Bankkonten, und wir können nicht garantieren, dass ein Anbieter das tut. Wir erbringen keine Rechts-, Steuer-, Anlage- oder sonstige regulierte Finanzberatung und übernehmen keine Firmengründung, Visa oder Einwanderung.',
  no_p2='Wo ein lizenzierter Fachmann nötig ist, sagen wir genau das.',
  facts_title='Unternehmen',
  facts=[('Rechtsträger','Platonaire LLC'),('Sitz','Kalifornien, USA'),('Arbeitet mit','USA & international'),
         ('Sprachen','RU · EN · ES · PT · DE'),('Intern gebaut','Web · E-Comm · Werbung'),('Erstanalyse','Kostenlos')],
  remote='Prodigy LAB arbeitet remote. Wir unterhalten kein Ladenbüro und beanspruchen keine Standorte, die wir nicht haben.',
  final_eyebrow='Kostenlose Erstanalyse',
  final_h2='Beschreiben Sie das Problem. Wir sagen Ihnen, was es aus unserer Sicht wirklich ist',
  final_lede='Kostenlos, unverbindlich und ohne Pflicht zu einem Gespräch. Liegt Ihre Situation außerhalb unseres Bereichs, erfahren Sie das — statt ein Angebot zu bekommen.',
  final_cta1='Analyse starten', final_cta2='Direkt schreiben',
  call='Anrufen', foot_priv='Datenschutz',
  foot_legal='Prodigy LAB ist kein Zahlungsdienstleister, keine Bank und kein lizenzierter Anbieter von Rechts-, Steuer- oder Finanzberatung.',
  nav=[('#problems','Was wir lösen'),('#how','Ablauf'),('#who','Wer wir sind')],
  problems=[
    ('01 — Zahlungen','Der Zahlungseingang steht still',
     'Stripe, Square oder PayPal haben das Konto geschlossen, halten Auszahlungen zurück, eine Reserve gesetzt — oder Ihre Branche ist ihnen unerwünscht.',
     ['Konto geschlossen oder eingefroren','Auszahlungen einbehalten, Reserve gesetzt','Händlerkonto abgelehnt','Hohe Chargeback-Quote','Braucht Ersatz-Processing']),
    ('02 — Banking','Die Bank sagte nein oder schloss das Konto',
     'Besonders bei US-Firma mit Gründer im Ausland oder einer Struktur, die der Bank kompliziert erscheint.',
     ['Konto geschlossen oder eingeschränkt','Antrag abgelehnt','Ausländischer Gründer, US-Gesellschaft','Braucht eine zweite Bank','Mehrwährung und grenzüberschreitend']),
    ('03 — Finanzierung','Sie brauchen das Geld, bevor es kommt',
     'Betriebsmittel, Ware, Löhne, Ausstattung — und die Liquiditätslücke dazwischen.',
     ['Die Bank hat abgelehnt','Liquiditätslücke','Waren- oder Geräteeinkauf','Kapital für Wachstum','Alternative Finanzierung']),
    ('04 — Wachstum','Traffic kommt, Umsatz nicht',
     'Die Akquise funktioniert auf dem Papier und scheitert in der Praxis, meist an einer Stelle.',
     ['Klicks ohne Bestellungen','Hohe Kundenkosten, schwacher ROAS','Anfragen, die nicht abschließen','Amazon oder Marktplätze stagnieren','Skalierung klappt nicht']),
    ('05 — Betrieb','Arbeit, die daran hängt, dass jemand daran denkt',
     'CRM, Automatisierung, die Übergabe zwischen Marketing und Vertrieb: alles von Hand.',
     ['Ein CRM, dem niemand traut','Manuelle, wiederkehrende Abläufe','Systeme, die nicht miteinander reden','Anfragen gehen bei der Übergabe verloren','Operative Engpässe']),
    ('06 — Infrastruktur','Funktionen, für die sich eine Stelle nicht lohnt',
     'Lohn und Personal, Sicherheit, laufende IT: nötig und wiederkehrend.',
     ['Lohnabrechnung und Personal-Compliance','Kein Sicherheitsprogramm','Ransomware-Risiko, Prüfung nötig','Managed IT und Help Desk','Microsoft 365, Cloud, Backups']),
    ('07 — Buchhaltung & Steuern','Die Bücher hinken, die Fristen nicht',
     'Buchhaltung, Monatsabschluss, Steuern, Aufarbeitung — vor allem wenn die Firma in den USA ist und Sie nicht.',
     ['Bücher müssen aufgearbeitet werden','Kein Monatsabschluss','Steuererklärung überfällig','Umsatzsteuer über Bundesstaaten','Braucht einen Teilzeit-CFO']),
    ('08 — Logistik & Lager','Sie sind über den Eigenversand hinausgewachsen',
     'Lager, Fulfilment, Amazon- und Walmart-Vorbereitung, Retouren, grenzüberschreitender Versand.',
     ['Braucht 3PL und Lager','Logistik frisst die Marge','Marktplatz-Vorbereitung','Retouren bleiben liegen','Internationaler Versand']),
    ('09 — Website & E-Commerce','Das Schaufenster, nach dem Sie beurteilt werden',
     'Der Teil, den wir seit Jahren selbst bauen.',
     ['Website oder Shop muss neu','Conversion und Checkout','Messung und Analytics fehlen','Braucht eine ehrliche Website-Analyse','Integrationen und einfache Automatisierung']),
  ],
  steps=[
    ('Sagen Sie, was nicht funktioniert','Eine kurze strukturierte Aufnahme, kein Kontaktformular. Was das Geschäft macht, was kaputt ist, was Sie schon versucht haben und wie dringend es ist.'),
    ('Wir analysieren — kostenlos','Wir melden uns mit dem, was wir für die eigentliche Engstelle halten, ob sich das jetzt lohnt und welche realistischen Wege es gibt. Ist es nicht unser Thema, sagen wir das.'),
    ('Wir lösen es oder leiten weiter','Was in unserer Kompetenz liegt, machen wir selbst. Alles andere geht an einen geprüften Fachpartner — und Sie wissen vorher, was wovon ist.'),
  ],
)
